"""
Unit tests for the cell generation functions.

@author: Paul T. Grogan <paul.grogan@asu.edu>"""

import unittest

from shapely.geometry import Polygon

from tatc.generation import (
    generate_cells_uniform_angular_spacing,
    generate_cells_uniform_spacing,
)


class TestCellGenerators(unittest.TestCase):
    """
    Unit tests for the cell generation functions.
    """
    def test_generate_equally_spaced_cells_no_mask_count(self):
        """
        Test that the number of cells generated by the equally spaced generator is correct.
        """
        points = generate_cells_uniform_angular_spacing(10, 10)
        num_samples = (360 / 10) * (180 / 10)
        self.assertEqual(len(points), num_samples)

    def test_generate_cells_uniform_spacing_mask_contains(self):
        """
        Test that the cells generated by the equally spaced generator
        are contained within the mask.
        """
        distance = 2000000
        mask = Polygon([[-100, 25], [-50, 25], [-50, -25], [-100, -25], [-100, 25]])
        points = generate_cells_uniform_spacing(distance, mask=mask)
        points.apply(lambda r: self.assertTrue(mask.contains(r.geometry)), axis=1)

    def test_generate_cells_uniform_spacing_mask_small(self):
        """
        Test that the cells generated by the equally spaced generator
        are empty when the mask is smaller than the cell size.
        """
        distance = 2000000
        mask = Polygon([[0, 0], [1, 0], [1, 1], [0, 1], [0, 0]])
        points = generate_cells_uniform_spacing(distance, mask=mask)
        self.assertEqual(len(points), 0)

    def test_generate_cells_uniform_spacing_mask_invalid(self):
        """
        Test that the cells generated by the equally spaced generator
        raise a ValueError when the mask is invalid.
        """
        distance = 2000000
        mask = Polygon([[-100, 25], [-50, 25], [-100, -25], [-50, -25], [-100, 25]])
        with self.assertRaises(ValueError):
            generate_cells_uniform_spacing(distance, mask=mask)

    def test_generate_equally_spaced_cells_no_mask_lat(self):
        """
        Test that the number of cells generated by the equally spaced 
        generator is correct when using latitude strips.
        """
        points = generate_cells_uniform_angular_spacing(10, 10, strips="lat")
        num_samples = 180 / 10
        self.assertEqual(len(points), num_samples)

    def test_generate_equally_spaced_cells_no_mask_lon(self):
        """
        Test that the number of cells generated by the equally spaced 
        generator is correct when using longitude strips.
        """
        points = generate_cells_uniform_angular_spacing(10, 10, strips="lon")
        num_samples = 360 / 10
        self.assertEqual(len(points), num_samples)
