"""
Unit tests for the point generation functions in tatc.generation.

@author Paul T. Grogan <paul.grogan@asu.edu>
"""

import unittest

import numpy as np
import pyproj
from shapely.geometry import Polygon
from shapely.ops import transform

from tatc import constants, utils
from tatc.generation import (
    generate_points_fibonacci_lattice,
    generate_points_uniform_angular_distance,
    generate_points_uniform_spacing,
)
from tatc.generation._grid import compute_point_id_uniform_spacing


class TestPointGenerators(unittest.TestCase):
    """
    Unit tests for the point generation functions in tatc.generation.
    """

    def test_generate_points_fibonacci_lattice_no_mask_count(self):
        """
        Test that the number of points generated by the Fibonacci lattice generator is correct.
        """
        distance = 2000000
        points = generate_points_fibonacci_lattice(distance)
        num_samples = utils.compute_number_samples(distance)
        self.assertEqual(len(points), num_samples)

    def test_generate_equally_spaced_points_no_mask_count(self):
        """
        Test that the number of points generated by the equally spaced generator is correct.
        """
        points = generate_points_uniform_angular_distance(10, 10)
        num_samples = (360 / 10) * (180 / 10)
        self.assertEqual(len(points), num_samples)

    def test_generate_points_fibonacci_lattice_no_mask_distance(self):
        """
        Test that the mean distance between points generated by the
        Fibonacci lattice generator is correct.
        """
        distance = 2000000
        points = generate_points_fibonacci_lattice(distance)
        test_points_m = points.to_crs("EPSG:32663")
        test_points_m["closest_neighbor"] = test_points_m.apply(
            lambda r: test_points_m[test_points_m.point_id != r.point_id]
            .distance(r.geometry)
            .min(),
            axis=1,
        )
        # mean should be within 10% of target sample distance
        self.assertAlmostEqual(
            test_points_m.closest_neighbor.mean(),
            distance,
            delta=0.10 * distance,
        )

    def test_generate_points_fibonacci_lattice_mask_count(self):
        """
        Test that the number of points generated by the Fibonacci
        lattice generator with a mask is correct.
        """
        distance = 2000000
        mask = Polygon([[-100, 25], [-50, 25], [-50, -25], [-100, -25], [-100, 25]])
        points = generate_points_fibonacci_lattice(distance, mask=mask)
        num_samples = utils.compute_number_samples(distance)
        transformer = pyproj.Transformer.from_crs(
            pyproj.CRS("EPSG:4326"), pyproj.CRS("EPSG:32663"), always_xy=True
        ).transform
        mask_m = transform(transformer, mask)
        self.assertAlmostEqual(
            len(points),
            int(num_samples * mask_m.area / constants.EARTH_SURFACE_AREA),
            delta=1,
        )

    def test_generate_points_fibonacci_lattice_mask_contains(self):
        """
        Test that all points generated by the Fibonacci lattice generator
        with a mask are contained within the mask.
        """
        distance = 2000000
        mask = Polygon([[-100, 25], [-50, 25], [-50, -25], [-100, -25], [-100, 25]])
        points = generate_points_fibonacci_lattice(distance, mask=mask)
        points.apply(lambda r: self.assertTrue(mask.contains(r.geometry)), axis=1)

    def test_generate_points_fibonacci_lattice_mask_distance(self):
        """
        Test that the mean distance between points generated by the
        Fibonacci lattice generator with a mask is correct.
        """
        distance = 2000000
        mask = Polygon([[-100, 25], [-50, 25], [-50, -25], [-100, -25], [-100, 25]])
        points = generate_points_fibonacci_lattice(distance, mask=mask)
        test_points_m = points.to_crs("EPSG:32663")
        test_points_m["closest_neighbor"] = test_points_m.apply(
            lambda r: test_points_m[test_points_m.point_id != r.point_id]
            .distance(r.geometry)
            .min(),
            axis=1,
        )
        # mean should be within 20% of target sample distance
        self.assertAlmostEqual(
            test_points_m.closest_neighbor.mean(),
            distance,
            delta=0.20 * distance,
        )

    def test_generate_points_uniform_spacing_no_mask_distance(self):
        """
        Test that the mean distance between points generated by the
        equally spaced generator is correct.
        """
        distance = 2000000
        points = generate_points_uniform_spacing(distance)
        test_points_m = points.to_crs("EPSG:32663")
        test_points_m["closest_neighbor"] = test_points_m.apply(
            lambda r: test_points_m[test_points_m.point_id != r.point_id]
            .distance(r.geometry)
            .min(),
            axis=1,
        )
        # mean should be within 10% of target sample distance
        self.assertAlmostEqual(
            test_points_m.closest_neighbor.mean(),
            distance,
            delta=0.10 * distance,
        )

    def test_generate_points_uniform_spacing_mask_contains(self):
        """
        Test that all points generated by the equally spaced generator
        with a mask are contained within the mask.
        """
        distance = 2000000
        mask = Polygon([[-100, 25], [-50, 25], [-50, -25], [-100, -25], [-100, 25]])
        points = generate_points_uniform_spacing(distance, mask=mask)
        points.apply(lambda r: self.assertTrue(mask.contains(r.geometry)), axis=1)

    def test_generate_points_uniform_spacing_mask_distance(self):
        """
        Test that the mean distance between points generated by the
        equally spaced generator with a mask is correct.
        """
        distance = 2000000
        mask = Polygon([[-100, 25], [-50, 25], [-50, -25], [-100, -25], [-100, 25]])
        points = generate_points_uniform_spacing(distance, mask=mask)
        test_points_m = points.to_crs("EPSG:32663")
        test_points_m["closest_neighbor"] = test_points_m.apply(
            lambda r: test_points_m[test_points_m.point_id != r.point_id]
            .distance(r.geometry)
            .min(),
            axis=1,
        )
        # mean should be within 20% of target sample distance
        self.assertAlmostEqual(
            test_points_m.closest_neighbor.mean(),
            distance,
            delta=0.20 * distance,
        )

    def test_generate_points_fibonacci_lattice_mask_small(self):
        """
        Test that the number of points generated by the Fibonacci
        lattice generator with a small mask is zero.
        """
        distance = 2000000
        mask = Polygon([[0, 0], [1, 0], [1, 1], [0, 1], [0, 0]])
        points = generate_points_fibonacci_lattice(distance, mask=mask)
        self.assertEqual(len(points), 0)

    def test_generate_points_uniform_spacing_mask_small(self):
        """
        Test that the number of points generated by the equally
        spaced generator with a small mask is zero.
        """
        distance = 2000000
        mask = Polygon([[0, 0], [1, 0], [1, 1], [0, 1], [0, 0]])
        points = generate_points_uniform_spacing(distance, mask=mask)
        self.assertEqual(len(points), 0)

    def test_generate_points_fibonacci_lattice_mask_invalid(self):
        """
        Test that the Fibonacci lattice generator raises a ValueError
        when given an invalid mask.
        """
        distance = 2000000
        mask = Polygon([[-100, 25], [-50, 25], [-100, -25], [-50, -25], [-100, 25]])
        with self.assertRaises(ValueError):
            generate_points_fibonacci_lattice(distance, mask=mask)

    def test_generate_points_uniform_spacing_mask_invalid(self):
        """
        Test that the equally spaced generator raises a ValueError
        when given an invalid mask.
        """
        distance = 2000000
        mask = Polygon([[-100, 25], [-50, 25], [-100, -25], [-50, -25], [-100, 25]])
        with self.assertRaises(ValueError):
            generate_points_uniform_spacing(distance, mask=mask)

    def test_generate_points_fibonacci_lattice_elevation(self):
        """
        Test that the elevation argument is propagated to the z-coordinate
        of every generated Fibonacci lattice point.
        """
        points = generate_points_fibonacci_lattice(3000000, elevation=500)
        self.assertTrue((points.geometry.apply(lambda g: g.z) == 500).all())

    def test_generate_points_uniform_spacing_elevation(self):
        """
        Test that the elevation argument is propagated to the z-coordinate
        of every generated equally spaced point.
        """
        points = generate_points_uniform_spacing(3000000, elevation=-200)
        self.assertTrue((points.geometry.apply(lambda g: g.z) == -200).all())

    def test_generate_points_fibonacci_lattice_no_poles(self):
        """
        Test that no generated Fibonacci lattice point sits exactly at
        either pole, per Gonzalez (2010)'s construction (referenced in the
        function's docstring).
        """
        points = generate_points_fibonacci_lattice(2000000)
        self.assertTrue((points.geometry.y.abs() < 90).all())

    def test_generate_points_fibonacci_lattice_matches_published_formula(self):
        """
        Test the first and last (by index) Fibonacci lattice point
        latitudes against Gonzalez (2010)'s closed-form placement formula,
        computed independently here rather than by importing the
        implementation's private helper.
        """
        distance = 2000000
        points = generate_points_fibonacci_lattice(distance)
        n = len(points)
        expected_first_latitude = np.degrees(np.arcsin(2 * 1 / (n + 2) - 1))
        expected_last_latitude = np.degrees(np.arcsin(2 * n / (n + 2) - 1))
        points_by_id = points.set_index("point_id")
        self.assertAlmostEqual(
            points_by_id.loc[0].geometry.y, expected_first_latitude, places=9
        )
        self.assertAlmostEqual(
            points_by_id.loc[n - 1].geometry.y, expected_last_latitude, places=9
        )

    def test_generate_points_fibonacci_lattice_antimeridian_crossing_mask(self):
        """
        Test the Fibonacci lattice generator with a mask crossing the
        antimeridian expressed in unwrapped longitude (170 to 190 degrees,
        rather than 170 to -170). All returned points should fall within
        the mask's own [170, 190] longitude convention -- including points
        whose natural longitude is negative (e.g. -175), which the
        implementation shifts by +360 to match the mask's unwrapped frame
        -- rather than being wrapped back to the standard [-180, 180]
        range.
        """
        mask = Polygon([[170, -10], [190, -10], [190, 10], [170, 10], [170, -10]])
        points = generate_points_fibonacci_lattice(500000, mask=mask)
        self.assertGreater(len(points), 0)
        self.assertTrue((points.geometry.x >= 170).all())
        self.assertTrue((points.geometry.x <= 190).all())
        # confirms points originally at negative longitude were included
        # via the +360 shift, not dropped
        self.assertTrue((points.geometry.x > 180).any())

    def test_generate_points_uniform_angular_distance_point_id_matches_grid_formula(
        self,
    ):
        """
        Test that every point_id returned by the equally spaced generator
        matches compute_point_id_uniform_spacing for that point's
        recovered (i, j) grid index, confirming point_id is a stable,
        dense (no gaps or collisions) enumeration for a global grid.
        """
        theta = 10
        points = generate_points_uniform_angular_distance(theta, theta)
        self.assertEqual(sorted(points.point_id), list(range(len(points))))
        for _, row in points.iterrows():
            i = round((row.geometry.x - (-180 + 0.5 * theta)) / theta)
            j = round((row.geometry.y - (-90 + 0.5 * theta)) / theta)
            self.assertEqual(
                compute_point_id_uniform_spacing(i, j, theta), row.point_id
            )
