name: Pylint
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pylint

    - name: Run pylint
      run: |
        pylint_output=$(pylint --rcfile=.pylintrc src/tatc --exit-zero)
        if echo "$pylint_output" | grep -q 'Your code has been rated at'; then
          score=$(echo "$pylint_output" | grep 'Your code has been rated at' | awk '{print $NF}' | cut -d'/' -f1) # Extract numeric part
          if (( $(echo "$score < 9.0" | bc -l) )); then
            echo "Found critical errors with score $score. Please fix and try again."
            exit 1
          else
            echo "No critical errors found. Score: $score"
          fi
        else
          echo "No pylint output found. Passing the build."
        fi